urms:
  config:
    loginServerUrlPrefix: http://urms.uat1.rs.com/passport
    shiroServerUrlPrefix: http://urms.uat1.rs.com
    anons:
       /index.html: anon
       /component/**: anon
       /**i18n/**: anon
       /**.js: anon
       /**.map: anon
       /**.woff: anon
       /login : anon
       /logout: anon
       /static: anon
       /metrics: anon
       /api-docs/**: anon
       /test/applicationAlive: anon