/**
 * Autogenerated by code generator (1.0.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yz.tc.model.base;

import java.util.Date;

public class RetryingDO {

    public static final String ID = "自增主键ID";
    public static final String BATCH_NO = "批次号";
    public static final String ERROR_CODE = "错误码";
    public static final String ERROR_MSG = "错误信息";
    public static final String DELETE_FLAG = "是否删除";
    public static final String DOING_TYPE = "操作类型";
    public static final String DOING_TYPE_NAME = "操作类型名称";
    public static final String FINAL_RESULT = "最终处理结果 0处理中 1成功 2失败";
    public static final String RETRY_COUNT = "补偿次数";
    public static final String CONTENT = "报文内容";
    public static final String TRADE_SCENE_NO = "业务场景编号";
    public static final String CREATE_TIME = "创建时间";
    public static final String CREATE_USER = "创建人ID";
    public static final String CREATE_USER_NAME = "创建人名称";
    public static final String UPDATE_TIME = "更新时间";
    public static final String UPDATE_USER = "更新人ID";
    public static final String UPDATE_USER_NAME = "更新人名称";
    public static final String IS_DELETED = "是否删除：0.未删除，1.已删除";


    /**
     * 自增主键ID
     */
    private Long id;

    /**
     * 批次号
     */
    private String batchNo;

    /**
     * 错误码
     */
    private String errorCode;

    /**
     * 错误信息
     */
    private String errorMsg;

    /**
     * 是否删除
     */
    private Byte deleteFlag;

    /**
     * 操作类型
     */
    private Byte doingType;

    /**
     * 操作类型名称
     */
    private String doingTypeName;

    /**
     * 最终处理结果 0处理中 1成功 2失败
     */
    private Byte finalResult;

    /**
     * 补偿次数
     */
    private Integer retryCount;

    /**
     * 报文内容
     */
    private String content;

    /**
     * 业务场景编号
     */
    private String tradeSceneNo;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 创建人ID
     */
    private String createUser;

    /**
     * 创建人名称
     */
    private String createUserName;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * 更新人ID
     */
    private String updateUser;

    /**
     * 更新人名称
     */
    private String updateUserName;

    /**
     * 是否删除：0.未删除，1.已删除
     */
    private Boolean isDeleted;
    

    public Long getId(){
        return id;
    }
    
    public void setId(Long id){
        this.id = id;
    }

    public String getBatchNo(){
        return batchNo;
    }
    
    public void setBatchNo(String batchNo){
        this.batchNo = batchNo;
    }

    public String getErrorCode(){
        return errorCode;
    }
    
    public void setErrorCode(String errorCode){
        this.errorCode = errorCode;
    }

    public String getErrorMsg(){
        return errorMsg;
    }
    
    public void setErrorMsg(String errorMsg){
        this.errorMsg = errorMsg;
    }

    public Byte getDeleteFlag(){
        return deleteFlag;
    }
    
    public void setDeleteFlag(Byte deleteFlag){
        this.deleteFlag = deleteFlag;
    }

    public Byte getDoingType(){
        return doingType;
    }
    
    public void setDoingType(Byte doingType){
        this.doingType = doingType;
    }

    public String getDoingTypeName(){
        return doingTypeName;
    }
    
    public void setDoingTypeName(String doingTypeName){
        this.doingTypeName = doingTypeName;
    }

    public Byte getFinalResult(){
        return finalResult;
    }
    
    public void setFinalResult(Byte finalResult){
        this.finalResult = finalResult;
    }

    public Integer getRetryCount(){
        return retryCount;
    }
    
    public void setRetryCount(Integer retryCount){
        this.retryCount = retryCount;
    }

    public String getContent(){
        return content;
    }
    
    public void setContent(String content){
        this.content = content;
    }

    public String getTradeSceneNo(){
        return tradeSceneNo;
    }
    
    public void setTradeSceneNo(String tradeSceneNo){
        this.tradeSceneNo = tradeSceneNo;
    }

    public Date getCreateTime(){
        return createTime;
    }
    
    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }

    public String getCreateUser(){
        return createUser;
    }
    
    public void setCreateUser(String createUser){
        this.createUser = createUser;
    }

    public String getCreateUserName(){
        return createUserName;
    }
    
    public void setCreateUserName(String createUserName){
        this.createUserName = createUserName;
    }

    public Date getUpdateTime(){
        return updateTime;
    }
    
    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }

    public String getUpdateUser(){
        return updateUser;
    }
    
    public void setUpdateUser(String updateUser){
        this.updateUser = updateUser;
    }

    public String getUpdateUserName(){
        return updateUserName;
    }
    
    public void setUpdateUserName(String updateUserName){
        this.updateUserName = updateUserName;
    }

    public Boolean getIsDeleted(){
        return isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted){
        this.isDeleted = isDeleted;
    }

    /**
    * The following custom property definition
    */

}